1st task
js-tasks-ru/jsbasic-20210906-2_maksym-shnaider pull request #2
Opened 2021-09-05 16:51 UTC by maxshnaider

2021-09-06 19:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-06 19:06 UTC, SinimaWath commented
Стоит вернуть 4 задачу. Если добавил, то над решать :)

2021-09-09 20:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-09 20:10 UTC, SinimaWath requested changes

2021-09-09 20:10 UTC, SinimaWath commented on 1-module/4-task/index.js
> +alert( checkSpam('innocent rabbit'))
Давай убирать информацию для тестирования и использовать: "npm test"

2021-09-11 14:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-11 14:59 UTC, SinimaWath approved these changes

2021-09-11 14:59 UTC, merged